-- Script: create_pedido_relacional.sql
-- Descrição: cria as tabelas `pedido` e `pedido_produto` (modelagem normalizada)
-- Uso recomendado (melhor integridade e consultas mais fáceis sobre itens do pedido)

-- Remover tabelas se já existirem (ordem: dependências primeiro)
DROP TABLE IF EXISTS pedido_produto;
DROP TABLE IF EXISTS pedido;

-- Tabela pedido: registra informações do pedido
-- Exemplo para MySQL / MariaDB
CREATE TABLE pedido (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente_id INT,
  data VARCHAR(50),
  status VARCHAR(50),
  CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON DELETE SET NULL
);

-- Tabela pedido_produto: relaciona pedidos e produtos (um pedido pode ter vários itens)
CREATE TABLE pedido_produto (
  pedido_id INT NOT NULL,
  produto_id INT NOT NULL,
  quantidade INT NOT NULL DEFAULT 1,
  PRIMARY KEY (pedido_id, produto_id),
  CONSTRAINT fk_pp_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id) ON DELETE CASCADE,
  CONSTRAINT fk_pp_produto FOREIGN KEY (produto_id) REFERENCES produto(id) ON DELETE RESTRICT
);

-- Índices para melhorar performance de consultas
CREATE INDEX idx_pedido_cliente ON pedido(cliente_id);
CREATE INDEX idx_pp_produto ON pedido_produto(produto_id);

-- Observações:
-- 1) Para PostgreSQL, substitua `INT AUTO_INCREMENT` por `SERIAL` ou `INT GENERATED BY DEFAULT AS IDENTITY`.
-- 2) A coluna `quantidade` foi adicionada para suportar múltiplas unidades do mesmo produto no pedido.
-- 3) A constraint ON DELETE CASCADE em `pedido_produto` remove automaticamente os itens quando um pedido é removido.

-- Exemplo de inserts de teste (ajuste ids conforme seus dados):
-- INSERT INTO pedido (cliente_id, data, status) VALUES (1, '2026-07-16', 'ABERTO');
-- INSERT INTO pedido_produto (pedido_id, produto_id, quantidade) VALUES (1, 2, 3);

